name: Test Self-hosted Runner

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Test runner environment
      run: |
        echo "🎉 Hello from self-hosted runner!"
        echo "Current user: $(whoami)"
        echo "Current directory: $(pwd)"
        echo "Node.js version: $(node --version)"
        echo "npm version: $(npm --version)"
        echo "Docker version: $(docker --version)"
        
    - name: Test system info
      run: |
        echo "OS Info:"
        lsb_release -a
        echo "Available space:"
        df -h
        echo "Memory info:"
        free -h    
  deploy:
    needs: test
    runs-on: self-hosted
    if: github.ref == 'refs/heads/master'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Build project
      run: npm run build
  
    - name: Deploy with Nginx
      run: |
        sudo rm -rf /var/www/html/*
        sudo cp -r build/* /var/www/html/
        sudo chown -R www-data:www-data /var/www/html
        sudo systemctl reload nginx
        
    - name: Health check
      run: |
        sleep 5
        curl -f http://localhost || exit 1